<?php if ( ! defined( 'ABSPATH' ) ) { exit; } get_header(); while ( have_posts() ) : the_post(); ?>
<article class="expert-section expert-prose"><p class="expert-eyebrow"><?php echo esc_html( get_post_type_object( get_post_type() )->labels->singular_name ); ?> · <?php echo esc_html( get_the_date() ); ?></p><h1><?php the_title(); ?></h1><p class="expert-muted"><?php esc_html_e( 'By', 'expert' ); ?> <?php the_author(); ?><?php if ( get_post_meta( get_the_ID(), '_expert_authored', true ) ) : ?> · <?php esc_html_e( 'Agent-authored; human revisions may follow', 'expert' ); ?><?php endif; ?></p>
<?php if ( 'expert_research' === get_post_type() ) : ?><p class="expert-notice"><?php esc_html_e( 'Research question — not established knowledge.', 'expert' ); ?> <?php echo esc_html( get_post_meta( get_the_ID(), '_expert_status', true ) ); ?></p><?php endif; ?>
<div><?php the_content(); ?></div><?php wp_link_pages(); ?>
<?php if ( 'expert_source' === get_post_type() ) : ?><section class="expert-provenance"><h2><?php esc_html_e( 'Source provenance', 'expert' ); ?></h2><dl><?php foreach ( array( 'publisher', 'author', 'published', 'retrieved', 'type', 'classification', 'primary', 'original_report', 'topic' ) as $expert_meta ) : $expert_value = get_post_meta( get_the_ID(), '_expert_' . $expert_meta, true ); if ( '' !== $expert_value ) : ?><dt><?php echo esc_html( ucfirst( str_replace( '_', ' ', $expert_meta ) ) ); ?></dt><dd><?php echo esc_html( $expert_value ); ?></dd><?php endif; endforeach; ?></dl><a href="<?php echo esc_url( get_post_meta( get_the_ID(), '_expert_url', true ) ); ?>" rel="nofollow noopener"><?php esc_html_e( 'Read the original source', 'expert' ); ?></a><h3><?php esc_html_e( 'Key claims', 'expert' ); ?></h3><ul><?php foreach ( (array) get_post_meta( get_the_ID(), '_expert_claims', true ) as $expert_claim ) : ?><li><?php echo esc_html( $expert_claim ); ?></li><?php endforeach; ?></ul></section><?php endif; ?>
<?php $expert_sources = (array) get_post_meta( get_the_ID(), '_expert_sources', true ); if ( $expert_sources ) : ?><section><h2><?php esc_html_e( 'Evidence and related knowledge', 'expert' ); ?></h2><ul><?php foreach ( $expert_sources as $expert_source_id ) : if ( 'publish' === get_post_status( $expert_source_id ) ) : ?><li><a href="<?php echo esc_url( get_permalink( $expert_source_id ) ); ?>"><?php echo esc_html( get_the_title( $expert_source_id ) ); ?></a></li><?php endif; endforeach; ?></ul></section><?php endif; ?>
<?php the_category( ', ' ); the_tags( '<p>', ', ', '</p>' ); $expert_edit_id = get_the_ID(); include get_template_directory() . '/templates/frontend-edit.php'; ?>
<?php if ( current_user_can( 'edit_post', get_the_ID() ) ) : $expert_revisions = wp_get_post_revisions( get_the_ID(), array( 'numberposts' => 10 ) ); if ( $expert_revisions ) : ?><details><summary><?php esc_html_e( 'Revision history', 'expert' ); ?></summary><?php foreach ( $expert_revisions as $expert_revision ) : ?><details><summary><?php $expert_author = get_user_by( 'id', $expert_revision->post_author ); echo esc_html( $expert_revision->post_date . ' · ' . ( $expert_author ? $expert_author->display_name : '' ) ); ?></summary><div><?php echo wp_kses_post( wpautop( $expert_revision->post_content ) ); ?></div></details><?php endforeach; ?></details><?php endif; endif; ?>
</article><?php if ( comments_open() || get_comments_number() ) { comments_template(); } endwhile; get_footer(); ?>
